name: On PR Opened

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kiloexabyte/runner-image:latest
    steps:
      - uses: actions/checkout@v6
      - run: op ci
